# -*- coding: utf-8 -*-
"""Resnet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuJg9QSuUwQMaTfnuZDRVnDofoqlEN3h
"""

# =========================================================
# 0️⃣ INSTALL DEPENDENCIES
# =========================================================
!pip install -q albumentations==1.3.1 roboflow opencv-python seaborn thop

# =========================================================
# 1️⃣ IMPORTS & SETUP
# =========================================================
import os, glob, random, time
import numpy as np
from collections import Counter
from PIL import Image
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torchvision import models

import albumentations as A
from albumentations.pytorch import ToTensorV2

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    average_precision_score
)
from sklearn.preprocessing import label_binarize

from roboflow import Roboflow
from thop import profile

device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
print("🔥 Device:", device)

# =========================================================
# 2️⃣ DOWNLOAD DATASET
# =========================================================
rf = Roboflow(api_key="I2du50GUFMWkImaaH0Wm")
project = rf.workspace("ahsan-khan-iw5ip").project("blood-group-detection-kmolp")
dataset = project.version(1).download("folder")
dataset_path = dataset.location

# =========================================================
# 3️⃣ LOAD DATA & SPLIT
# =========================================================
def load_all_data(path):
    files, labels = [], []
    classes = sorted(os.listdir(os.path.join(path, "train")))
    for i, cls in enumerate(classes):
        for split in ["train", "valid", "test"]:
            p = os.path.join(path, split, cls)
            if os.path.exists(p):
                imgs = glob.glob(p + "/*")
                files.extend(imgs)
                labels.extend([i] * len(imgs))
    return files, labels, classes

files, labels, classes = load_all_data(dataset_path)

X_train, X_tmp, y_train, y_tmp = train_test_split(
    files, labels, test_size=0.30, stratify=labels, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_tmp, y_tmp, test_size=0.50, stratify=y_tmp, random_state=42
)

cnt = Counter(y_train)
print("📊 Train Distribution:", cnt)

# =========================================================
# 4️⃣ AUGMENTATION
# =========================================================
train_tfms = A.Compose([
    A.Resize(224, 224),
    A.HorizontalFlip(p=0.5),
    A.ShiftScaleRotate(shift_limit=0.05, scale_limit=0.1, rotate_limit=10, p=0.4),
    A.Normalize(),
    ToTensorV2()
])

val_tfms = A.Compose([
    A.Resize(224, 224),
    A.Normalize(),
    ToTensorV2()
])

# =========================================================
# 5️⃣ DATASET & DATALOADERS
# =========================================================
class BloodDataset(Dataset):
    def __init__(self, files, labels, tfm):
        self.files = files
        self.labels = labels
        self.tfm = tfm

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        img = np.array(Image.open(self.files[idx]).convert("RGB"))
        img = self.tfm(image=img)["image"]
        return img, torch.tensor(self.labels[idx])

weights = [1.0 / cnt[l] for l in y_train]
sampler = WeightedRandomSampler(weights, len(weights), replacement=True)

train_dl = DataLoader(
    BloodDataset(X_train, y_train, train_tfms),
    batch_size=32,
    sampler=sampler,
    num_workers=2
)

val_dl = DataLoader(
    BloodDataset(X_val, y_val, val_tfms),
    batch_size=64,
    num_workers=2
)

test_dl = DataLoader(
    BloodDataset(X_test, y_test, val_tfms),
    batch_size=64,
    num_workers=2
)

# =========================================================
# 6️⃣ MODEL — RESNET50
# =========================================================
model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
in_features = model.fc.in_features
model.fc = nn.Linear(in_features, len(classes))
model = model.to(device)

print("✅ ResNet50 Loaded")

# =========================================================
# 7️⃣ LOSS, OPTIMIZER & LR SCHEDULER
# =========================================================
class_weights = torch.tensor(
    [1.0 / cnt[i] for i in range(len(classes))],
    device=device
)

criterion = nn.CrossEntropyLoss(weight=class_weights)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=1e-4)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=25)

scaler = torch.cuda.amp.GradScaler()

# =========================================================
# 8️⃣ TRAINING
# =========================================================
EPOCHS = 25
best_val = 0

train_acc_hist, val_acc_hist = [], []
train_loss_hist, val_loss_hist = [], []
lr_hist = []

for epoch in range(EPOCHS):
    model.train()
    tp, ty = [], []
    running_loss = 0.0

    for x, y in tqdm(train_dl, desc=f"Epoch {epoch+1}/{EPOCHS}"):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()

        with torch.cuda.amp.autocast():
            out = model(x)
            loss = criterion(out, y)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        tp += out.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()

    scheduler.step()
    lr_hist.append(optimizer.param_groups[0]["lr"])

    train_loss = running_loss / len(train_dl)
    tr_acc = accuracy_score(ty, tp)

    model.eval()
    vp, vy = [], []
    val_running_loss = 0.0

    with torch.no_grad():
        for x, y in val_dl:
            x, y = x.to(device), y.to(device)
            out = model(x)
            loss = criterion(out, y)

            val_running_loss += loss.item()
            vp += out.argmax(1).cpu().tolist()
            vy += y.cpu().tolist()

    val_loss = val_running_loss / len(val_dl)
    v_acc = accuracy_score(vy, vp)

    train_acc_hist.append(tr_acc)
    val_acc_hist.append(v_acc)
    train_loss_hist.append(train_loss)
    val_loss_hist.append(val_loss)

    print(f"📊 Epoch {epoch+1}: Train Acc={tr_acc:.4f} | Val Acc={v_acc:.4f}")

    if v_acc > best_val:
        best_val = v_acc
        torch.save(model.state_dict(), "Best_ResNet50.pth")
        print("✅ Best model saved")

# =========================================================
# 9️⃣ TESTING
# =========================================================
model.load_state_dict(torch.load("Best_ResNet50.pth"))
model.eval()

tp, ty, y_prob = [], [], []

with torch.no_grad():
    for x, y in test_dl:
        x = x.to(device)
        out = model(x)
        prob = torch.softmax(out, dim=1)

        tp += out.argmax(1).cpu().tolist()
        ty += y.tolist()
        y_prob.extend(prob.cpu().numpy())

y_true = np.array(ty)
y_pred = np.array(tp)
y_prob = np.array(y_prob)

print("\n🎯 TEST ACCURACY:", accuracy_score(y_true, y_pred))
print("\n📄 CLASSIFICATION REPORT:\n")
print(classification_report(y_true, y_pred, target_names=classes))

torch.save(model.state_dict(), "ResNet50_Final.pth")

# =========================================================
# 🔟 CONFUSION MATRIX
# =========================================================
cm = confusion_matrix(y_true, y_pred, normalize="true")

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, cmap="Blues", fmt=".2f",
            xticklabels=classes, yticklabels=classes)
plt.title("Normalized Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# =========================================================
# 1️⃣1️⃣ ROC & PR CURVES
# =========================================================
y_true_bin = label_binarize(y_true, classes=range(len(classes)))

roc_auc_macro = roc_auc_score(y_true_bin, y_prob, average="macro", multi_class="ovr")
print("📈 ROC-AUC (Macro):", round(roc_auc_macro, 4))

plt.figure(figsize=(7,6))
for i, cls in enumerate(classes):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_prob[:, i])
    plt.plot(fpr, tpr, label=cls)

plt.plot([0,1],[0,1],"k--")
plt.legend()
plt.title("ROC Curves")
plt.show()

plt.figure(figsize=(7,6))
for i, cls in enumerate(classes):
    p, r, _ = precision_recall_curve(y_true_bin[:, i], y_prob[:, i])
    ap = average_precision_score(y_true_bin[:, i], y_prob[:, i])
    plt.plot(r, p, label=f"{cls} (AP={ap:.2f})")

plt.legend()
plt.title("Precision-Recall Curves")
plt.show()

# =========================================================
# 1️⃣2️⃣ MODEL COMPLEXITY
# =========================================================
dummy = torch.randn(1,3,224,224).to(device)
flops, params = profile(model, inputs=(dummy,), verbose=False)

print("Parameters (M):", params/1e6)
print("FLOPs (GFLOPs):", flops/1e9)

# =========================================================
# 1️⃣3️⃣ INFERENCE TIME
# =========================================================
starter, ender = torch.cuda.Event(True), torch.cuda.Event(True)
starter.record()
_ = model(dummy)
ender.record()
torch.cuda.synchronize()

print("Inference Time (ms):", starter.elapsed_time(ender))

# =========================================================
# 1️⃣4️⃣ 5-FOLD CV (ON TEST PREDICTIONS)
# =========================================================
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = []

for fold, (_, idx) in enumerate(skf.split(y_true, y_true)):
    acc_fold = accuracy_score(y_true[idx], y_pred[idx])
    cv_scores.append(acc_fold)
    print(f"Fold {fold+1} Accuracy: {acc_fold:.4f}")

print("CV Mean:", np.mean(cv_scores))
print("CV Std:", np.std(cv_scores))

print("\n✅ ALL RESNET50 RESULTS GENERATED")