# -*- coding: utf-8 -*-
"""MobileViT-V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHLj3Wsg72-v4v7UNhu68K4bURHyJ9aL
"""

# =========================================================
# 0️⃣ INSTALL DEPENDENCIES
# =========================================================
!pip install -q timm albumentations==1.3.1 roboflow opencv-python matplotlib

# =========================================================
# 1️⃣ IMPORTS & SETUP
# =========================================================
import os, glob, random
import numpy as np
from collections import Counter
from PIL import Image
from tqdm.auto import tqdm
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

import albumentations as A
from albumentations.pytorch import ToTensorV2

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

import timm
from roboflow import Roboflow

# ---------------- DEVICE ----------------
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
print("🔥 Device:", device)

# =========================================================
# 2️⃣ DOWNLOAD DATASET
# =========================================================
rf = Roboflow(api_key="I2du50GUFMWkImaaH0Wm")
project = rf.workspace("ahsan-khan-iw5ip").project("blood-group-detection-kmolp")
dataset = project.version(1).download("folder")
dataset_path = dataset.location

# =========================================================
# 3️⃣ LOAD DATA & SPLIT
# =========================================================
def load_all_data(path):
    files, labels = [], []
    classes = sorted(os.listdir(os.path.join(path, "train")))
    for i, cls in enumerate(classes):
        for split in ["train", "valid", "test"]:
            p = os.path.join(path, split, cls)
            if os.path.exists(p):
                imgs = glob.glob(p + "/*")
                files.extend(imgs)
                labels.extend([i] * len(imgs))
    return files, labels, classes

files, labels, classes = load_all_data(dataset_path)

X_train, X_tmp, y_train, y_tmp = train_test_split(
    files, labels, test_size=0.30, stratify=labels, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_tmp, y_tmp, test_size=0.50, stratify=y_tmp, random_state=42
)

cnt = Counter(y_train)
print("📊 Train Distribution:", cnt)

# =========================================================
# 4️⃣ AUGMENTATION (FINGERPRINT SAFE)
# =========================================================
train_tfms = A.Compose([
    A.Resize(224, 224),
    A.HorizontalFlip(p=0.5),
    A.Rotate(limit=8, p=0.3),
    A.RandomBrightnessContrast(0.1, 0.1, p=0.3),
    A.Normalize(),
    ToTensorV2()
])

val_tfms = A.Compose([
    A.Resize(224, 224),
    A.Normalize(),
    ToTensorV2()
])

# =========================================================
# 5️⃣ DATASET & DATALOADERS
# =========================================================
class FingerprintDataset(Dataset):
    def __init__(self, files, labels, tfm):
        self.files = files
        self.labels = labels
        self.tfm = tfm

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        img = np.array(Image.open(self.files[idx]).convert("RGB"))
        img = self.tfm(image=img)["image"]
        return img, torch.tensor(self.labels[idx])

weights = [1.0 / cnt[l] for l in y_train]
sampler = WeightedRandomSampler(weights, len(weights), replacement=True)

train_dl = DataLoader(
    FingerprintDataset(X_train, y_train, train_tfms),
    batch_size=32, sampler=sampler, num_workers=2
)
val_dl = DataLoader(
    FingerprintDataset(X_val, y_val, val_tfms),
    batch_size=64, num_workers=2
)
test_dl = DataLoader(
    FingerprintDataset(X_test, y_test, val_tfms),
    batch_size=64, num_workers=2
)

# =========================================================
# 6️⃣ MODEL — MobileViT-V2 (NEW MODEL)
# =========================================================
model = timm.create_model(
    "mobilevitv2_100",
    pretrained=True,
    num_classes=len(classes),
    drop_rate=0.3
).to(device)

print("✅ MobileViT-V2 Loaded")

# =========================================================
# 7️⃣ LOSS, OPTIMIZER & SCHEDULER
# =========================================================
class_weights = torch.tensor(
    [1.0 / cnt[i] for i in range(len(classes))],
    device=device
)

criterion = nn.CrossEntropyLoss(
    weight=class_weights,
    label_smoothing=0.1
)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=2e-4,
    weight_decay=1e-4
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=25
)

scaler = torch.cuda.amp.GradScaler()

# =========================================================
# 8️⃣ TRAINING WITH LOSS & LR LOGGING
# =========================================================
EPOCHS = 25
best_val = 0

train_loss_hist, val_loss_hist, lr_hist = [], [], []

for epoch in range(EPOCHS):
    model.train()
    train_loss = 0
    tp, ty = [], []

    current_lr = optimizer.param_groups[0]["lr"]
    lr_hist.append(current_lr)

    for x, y in tqdm(train_dl, desc=f"Epoch {epoch+1}/{EPOCHS}"):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()

        with torch.cuda.amp.autocast():
            out = model(x)
            loss = criterion(out, y)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss += loss.item()
        tp += out.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()

    scheduler.step()

    train_loss /= len(train_dl)
    train_acc = accuracy_score(ty, tp)

    # -------- VALIDATION --------
    model.eval()
    val_loss = 0
    vp, vy = [], []

    with torch.no_grad():
        for x, y in val_dl:
            x, y = x.to(device), y.to(device)
            out = model(x)
            loss = criterion(out, y)

            val_loss += loss.item()
            vp += out.argmax(1).cpu().tolist()
            vy += y.cpu().tolist()

    val_loss /= len(val_dl)
    val_acc = accuracy_score(vy, vp)

    train_loss_hist.append(train_loss)
    val_loss_hist.append(val_loss)

    print(
        f"📊 Epoch {epoch+1} | "
        f"LR={current_lr:.6f} | "
        f"Train Loss={train_loss:.4f}, Acc={train_acc:.4f} | "
        f"Val Loss={val_loss:.4f}, Acc={val_acc:.4f}"
    )

    if val_acc > best_val:
        best_val = val_acc
        torch.save(model.state_dict(), "Best_MobileViTv2.pth")
        print("✅ Best model saved")

# =========================================================
# 9️⃣ TESTING
# =========================================================
model.load_state_dict(torch.load("Best_MobileViTv2.pth"))
model.eval()

tp, ty = [], []
with torch.no_grad():
    for x, y in test_dl:
        x, y = x.to(device), y.to(device)
        out = model(x)
        tp += out.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()

print("\n🎯 TEST ACCURACY:", accuracy_score(ty, tp))
print("\n📄 CLASSIFICATION REPORT:\n")
print(classification_report(ty, tp, target_names=classes))

# =========================================================
# 🔟 PLOT LOSS & LEARNING RATE
# =========================================================
epochs = range(1, EPOCHS + 1)

plt.figure(figsize=(14,5))

plt.subplot(1,2,1)
plt.plot(epochs, train_loss_hist, label="Train Loss")
plt.plot(epochs, val_loss_hist, label="Val Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training & Validation Loss")
plt.legend()
plt.grid(True)

plt.subplot(1,2,2)
plt.plot(epochs, lr_hist)
plt.xlabel("Epochs")
plt.ylabel("Learning Rate")
plt.title("Learning Rate Schedule")
plt.grid(True)

plt.show()

# =========================================================
# 🔟 SAVE FINAL MODEL
# =========================================================
torch.save(model.state_dict(), "MobileViTv2_Final.pth")
print("✅ Final model saved")

# =========================================================
# 🔬 JOURNAL / CONFERENCE POST-ANALYSIS (ALL IN ONE)
# =========================================================
import time
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import (
    confusion_matrix,
    roc_curve,
    auc,
    precision_recall_curve,
    classification_report
)
from sklearn.preprocessing import label_binarize

# =========================================================
# 1️⃣ GET PREDICTIONS & PROBABILITIES
# =========================================================
model.eval()

y_true, y_pred, y_prob = [], [], []

with torch.no_grad():
    for x, y in test_dl:
        x = x.to(device)
        outputs = model(x)
        probs = torch.softmax(outputs, dim=1)

        y_true.extend(y.numpy())
        y_pred.extend(probs.argmax(1).cpu().numpy())
        y_prob.extend(probs.cpu().numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_prob = np.array(y_prob)

# =========================================================
# 2️⃣ CONFUSION MATRIX (RAW + NORMALIZED)
# =========================================================
cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype(float) / cm.sum(axis=1)[:, None]

plt.figure(figsize=(14,6))

plt.subplot(1,2,1)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix (Raw)")
plt.xlabel("Predicted")
plt.ylabel("True")

plt.subplot(1,2,2)
sns.heatmap(cm_norm, annot=True, fmt=".2f", cmap="Greens",
            xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix (Normalized)")
plt.xlabel("Predicted")
plt.ylabel("True")

plt.tight_layout()
plt.show()

# =========================================================
# 3️⃣ ROC CURVES (MULTI-CLASS)
# =========================================================
y_bin = label_binarize(y_true, classes=range(len(classes)))
n_classes = y_bin.shape[1]

plt.figure(figsize=(8,6))
auc_scores = {}

for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_bin[:, i], y_prob[:, i])
    roc_auc = auc(fpr, tpr)
    auc_scores[classes[i]] = roc_auc
    plt.plot(fpr, tpr, label=f"{classes[i]} (AUC={roc_auc:.3f})")

plt.plot([0,1], [0,1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Multi-Class ROC Curve")
plt.legend()
plt.grid(True)
plt.show()

# =========================================================
# 4️⃣ PRECISION–RECALL CURVES
# =========================================================
plt.figure(figsize=(8,6))

for i in range(n_classes):
    precision, recall, _ = precision_recall_curve(
        y_bin[:, i], y_prob[:, i]
    )
    plt.plot(recall, precision, label=classes[i])

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision–Recall Curves")
plt.legend()
plt.grid(True)
plt.show()

# =========================================================
# 5️⃣ SAVE METRICS TO CSV (PAPER TABLES)
# =========================================================
report = classification_report(
    y_true, y_pred, target_names=classes, output_dict=True
)

df_report = pd.DataFrame(report).transpose()
df_report.to_csv("classification_report.csv")

df_auc = pd.DataFrame.from_dict(
    auc_scores, orient="index", columns=["AUC"]
)
df_auc.to_csv("auc_scores.csv")

print("✅ Saved: classification_report.csv, auc_scores.csv")

# =========================================================
# 6️⃣ INFERENCE TIME ANALYSIS
# =========================================================
times = []

with torch.no_grad():
    for x, _ in test_dl:
        x = x.to(device)
        start = time.time()
        _ = model(x)
        end = time.time()
        times.append(end - start)

avg_time_ms = (np.mean(times) / test_dl.batch_size) * 1000
print(f"⏱️ Average Inference Time: {avg_time_ms:.2f} ms/image")

import gc
import torch

torch.cuda.empty_cache()
gc.collect()

# =========================================================
# 🔍 MEMORY-SAFE GRAD-CAM (BATCH=1)
# =========================================================
import torch.nn.functional as F

# ---- Force single image only ----
model.eval()

# Move model to GPU only if memory allows
use_gpu = torch.cuda.is_available()
device_cam = "cuda" if use_gpu else "cpu"

model = model.to(device_cam)

# Pick ONE image only
img, label = test_dl.dataset[0]
x = img.unsqueeze(0).to(device_cam)   # shape: (1,3,224,224)

# =========================================================
# GRAD-CAM CLASS (SAFE)
# =========================================================
class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.gradients = None
        self.activations = None

        target_layer.register_forward_hook(self._forward_hook)
        target_layer.register_full_backward_hook(self._backward_hook)

    def _forward_hook(self, module, input, output):
        self.activations = output

    def _backward_hook(self, module, grad_input, grad_output):
        self.gradients = grad_output[0]

    def generate(self, x, class_idx):
        self.model.zero_grad()

        output = self.model(x)
        score = output[0, class_idx]   # ✅ scalar
        score.backward()

        weights = self.gradients.mean(dim=(2, 3), keepdim=True)
        cam = (weights * self.activations).sum(dim=1)
        cam = F.relu(cam)

        cam = cam - cam.min()
        cam = cam / (cam.max() + 1e-8)
        return cam


# =========================================================
# FIND LAST CONV LAYER (MobileViT SAFE)
# =========================================================
target_layer = None
for m in reversed(list(model.modules())):
    if isinstance(m, torch.nn.Conv2d):
        target_layer = m
        break

assert target_layer is not None, "❌ No Conv2D layer found"

gradcam = GradCAM(model, target_layer)

# =========================================================
# RUN GRAD-CAM
# =========================================================
with torch.enable_grad():
    pred_class = model(x).argmax(1).item()
    cam = gradcam.generate(x, pred_class)

cam_img = cam[0].detach().cpu().numpy()

# =========================================================
# VISUALIZATION
# =========================================================
import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))
plt.imshow(cam_img, cmap="jet")
plt.title(f"Grad-CAM | Predicted: {classes[pred_class]}")
plt.axis("off")
plt.colorbar()
plt.show()

# =========================================================
# 📊 JOURNAL / CONFERENCE POST-ANALYSIS (NO GRAD-CAM)
# =========================================================
import os
import time
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_curve,
    auc,
    precision_recall_curve
)
from sklearn.preprocessing import label_binarize

# =========================================================
# 1️⃣ GET PREDICTIONS & PROBABILITIES
# =========================================================
model.eval()

y_true, y_pred, y_prob = [], [], []

with torch.no_grad():
    for x, y in test_dl:
        x = x.to(device)
        out = model(x)
        probs = torch.softmax(out, dim=1)

        y_true.extend(y.numpy())
        y_pred.extend(probs.argmax(1).cpu().numpy())
        y_prob.extend(probs.cpu().numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_prob = np.array(y_prob)

# =========================================================
# 2️⃣ CONFUSION MATRIX (RAW + NORMALIZED)
# =========================================================
cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

plt.figure(figsize=(14,6))

plt.subplot(1,2,1)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix (Raw)")
plt.xlabel("Predicted")
plt.ylabel("True")

plt.subplot(1,2,2)
sns.heatmap(cm_norm, annot=True, fmt=".2f", cmap="Greens",
            xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix (Normalized)")
plt.xlabel("Predicted")
plt.ylabel("True")

plt.tight_layout()
plt.show()

# =========================================================
# 3️⃣ ROC CURVES (MULTI-CLASS)
# =========================================================
y_bin = label_binarize(y_true, classes=range(len(classes)))
n_classes = y_bin.shape[1]

plt.figure(figsize=(8,6))
auc_scores = {}

for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_bin[:, i], y_prob[:, i])
    roc_auc = auc(fpr, tpr)
    auc_scores[classes[i]] = roc_auc
    plt.plot(fpr, tpr, label=f"{classes[i]} (AUC={roc_auc:.3f})")

plt.plot([0,1], [0,1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Multi-Class ROC Curve")
plt.legend()
plt.grid(True)
plt.show()

# =========================================================
# 4️⃣ PRECISION–RECALL CURVES
# =========================================================
plt.figure(figsize=(8,6))

for i in range(n_classes):
    precision, recall, _ = precision_recall_curve(
        y_bin[:, i], y_prob[:, i]
    )
    plt.plot(recall, precision, label=classes[i])

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision–Recall Curves")
plt.legend()
plt.grid(True)
plt.show()

# =========================================================
# 5️⃣ SAVE METRICS TO CSV (FOR JOURNAL TABLES)
# =========================================================
report = classification_report(
    y_true, y_pred, target_names=classes, output_dict=True
)

df_report = pd.DataFrame(report).transpose()
df_report.to_csv("classification_report.csv")

df_auc = pd.DataFrame.from_dict(
    auc_scores, orient="index", columns=["AUC"]
)
df_auc.to_csv("auc_scores.csv")

print("✅ Saved CSV files: classification_report.csv, auc_scores.csv")

# =========================================================
# 6️⃣ INFERENCE TIME (EFFICIENCY ANALYSIS)
# =========================================================
times = []

with torch.no_grad():
    for x, _ in test_dl:
        x = x.to(device)
        start = time.time()
        _ = model(x)
        end = time.time()
        times.append(end - start)

avg_time_ms = (np.mean(times) / test_dl.batch_size) * 1000
print(f"⏱️ Average Inference Time: {avg_time_ms:.2f} ms/image")

# =========================================================
# 7️⃣ MODEL SIZE & PARAMETERS
# =========================================================
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"📦 Total Parameters: {total_params/1e6:.2f} Million")
print(f"🧠 Trainable Parameters: {trainable_params/1e6:.2f} Million")

# =========================================================
# 8️⃣ MODEL CALIBRATION (ECE)
# =========================================================
def expected_calibration_error(y_true, y_prob, n_bins=10):
    bins = np.linspace(0, 1, n_bins + 1)
    confidences = np.max(y_prob, axis=1)
    predictions = np.argmax(y_prob, axis=1)

    ece = 0
    for i in range(n_bins):
        mask = (confidences > bins[i]) & (confidences <= bins[i+1])
        if mask.sum() > 0:
            acc = (predictions[mask] == y_true[mask]).mean()
            conf = confidences[mask].mean()
            ece += abs(acc - conf) * mask.mean()
    return ece

ece = expected_calibration_error(y_true, y_prob)
print(f"📐 Expected Calibration Error (ECE): {ece:.4f}")

# =========================================================
# 9️⃣ QUALITATIVE RESULTS (SAVE SAMPLE PREDICTIONS)
# =========================================================
os.makedirs("qualitative_results", exist_ok=True)

model.eval()
with torch.no_grad():
    for i in range(5):
        img, label = test_dl.dataset[i]
        img_t = img.unsqueeze(0).to(device)
        pred = model(img_t).argmax(1).item()

        plt.imshow(img.permute(1,2,0).cpu())
        plt.title(f"GT: {classes[label]} | Pred: {classes[pred]}")
        plt.axis("off")
        plt.savefig(f"qualitative_results/sample_{i}.png", dpi=300)
        plt.close()

print("🖼️ Qualitative prediction images saved")