# -*- coding: utf-8 -*-
"""ConvNeXt-Small.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjpJCJx7mvFUB7yP_ae36dDjIKiHto-7
"""

# =========================================================
# 0️⃣ INSTALL DEPENDENCIES
# =========================================================
!pip install -q timm albumentations==1.3.1 roboflow opencv-python

# =========================================================
# 1️⃣ IMPORTS & SETUP
# =========================================================
import os, glob, random
import numpy as np
from collections import Counter
from PIL import Image
from tqdm.auto import tqdm
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

import albumentations as A
from albumentations.pytorch import ToTensorV2

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

import timm
from roboflow import Roboflow

device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
print("🔥 Device:", device)

# =========================================================
# 2️⃣ DOWNLOAD DATASET
# =========================================================
rf = Roboflow(api_key="I2du50GUFMWkImaaH0Wm")
project = rf.workspace("ahsan-khan-iw5ip").project("blood-group-detection-kmolp")
dataset = project.version(1).download("folder")
dataset_path = dataset.location

# =========================================================
# 3️⃣ LOAD DATA & SPLIT
# =========================================================
def load_all_data(path):
    files, labels = [], []
    classes = sorted(os.listdir(os.path.join(path, "train")))
    for i, cls in enumerate(classes):
        for split in ["train", "valid", "test"]:
            p = os.path.join(path, split, cls)
            if os.path.exists(p):
                imgs = glob.glob(p + "/*")
                files.extend(imgs)
                labels.extend([i] * len(imgs))
    return files, labels, classes

files, labels, classes = load_all_data(dataset_path)

X_train, X_tmp, y_train, y_tmp = train_test_split(
    files, labels, test_size=0.30, stratify=labels, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_tmp, y_tmp, test_size=0.50, stratify=y_tmp, random_state=42
)

cnt = Counter(y_train)
print("📊 Train Distribution:", cnt)

# =========================================================
# 4️⃣ AUGMENTATION (SAFE & EFFECTIVE)
# =========================================================
train_tfms = A.Compose([
    A.Resize(224, 224),
    A.HorizontalFlip(p=0.5),
    A.ShiftScaleRotate(
        shift_limit=0.05,
        scale_limit=0.1,
        rotate_limit=10,
        p=0.4
    ),
    A.Normalize(),
    ToTensorV2()
])

val_tfms = A.Compose([
    A.Resize(224, 224),
    A.Normalize(),
    ToTensorV2()
])

# =========================================================
# 5️⃣ DATASET & DATALOADERS
# =========================================================
class BloodDataset(Dataset):
    def __init__(self, files, labels, tfm):
        self.files = files
        self.labels = labels
        self.tfm = tfm

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        img = np.array(Image.open(self.files[idx]).convert("RGB"))
        img = self.tfm(image=img)["image"]
        return img, torch.tensor(self.labels[idx])

weights = [1.0 / cnt[l] for l in y_train]
sampler = WeightedRandomSampler(weights, len(weights), replacement=True)

train_dl = DataLoader(
    BloodDataset(X_train, y_train, train_tfms),
    batch_size=32,
    sampler=sampler,
    num_workers=2
)

val_dl = DataLoader(
    BloodDataset(X_val, y_val, val_tfms),
    batch_size=64,
    num_workers=2
)

test_dl = DataLoader(
    BloodDataset(X_test, y_test, val_tfms),
    batch_size=64,
    num_workers=2
)

# =========================================================
# 6️⃣ MODEL — ConvNeXt Small
# =========================================================
model = timm.create_model(
    "convnext_small",
    pretrained=True,
    num_classes=len(classes)
).to(device)

print("✅ ConvNeXt-Small Loaded")

# =========================================================
# 7️⃣ LOSS, OPTIMIZER & LR SCHEDULER
# =========================================================
class_weights = torch.tensor(
    [1.0 / cnt[i] for i in range(len(classes))],
    device=device
)

criterion = nn.CrossEntropyLoss(weight=class_weights)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=2e-4,
    weight_decay=1e-4
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=25
)

scaler = torch.cuda.amp.GradScaler()

# =========================================================
# 8️⃣ TRAINING (METRICS TRACKING)
# =========================================================
EPOCHS = 25
best_val = 0

train_acc_hist, val_acc_hist = [], []
train_loss_hist, val_loss_hist = [], []
lr_hist = []

for epoch in range(EPOCHS):
    model.train()
    tp, ty = [], []
    running_loss = 0.0

    for x, y in tqdm(train_dl, desc=f"Epoch {epoch+1}/{EPOCHS}"):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()

        with torch.cuda.amp.autocast():
            out = model(x)
            loss = criterion(out, y)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        tp += out.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()

    scheduler.step()
    lr_hist.append(optimizer.param_groups[0]["lr"])

    train_loss = running_loss / len(train_dl)
    tr_acc = accuracy_score(ty, tp)

    # -------- VALIDATION --------
    model.eval()
    vp, vy = [], []
    val_running_loss = 0.0

    with torch.no_grad():
        for x, y in val_dl:
            x, y = x.to(device), y.to(device)
            out = model(x)
            loss = criterion(out, y)

            val_running_loss += loss.item()
            vp += out.argmax(1).cpu().tolist()
            vy += y.cpu().tolist()

    val_loss = val_running_loss / len(val_dl)
    v_acc = accuracy_score(vy, vp)

    train_acc_hist.append(tr_acc)
    val_acc_hist.append(v_acc)
    train_loss_hist.append(train_loss)
    val_loss_hist.append(val_loss)

    print(
        f"📊 Epoch {epoch+1}: "
        f"Train Acc={tr_acc:.4f} | Val Acc={v_acc:.4f} | "
        f"Train Loss={train_loss:.4f} | Val Loss={val_loss:.4f}"
    )

    if v_acc > best_val:
        best_val = v_acc
        torch.save(model.state_dict(), "Best_ConvNeXtSmall.pth")
        print("✅ Best model saved")

# =========================================================
# 9️⃣ TESTING
# =========================================================
model.load_state_dict(torch.load("Best_ConvNeXtSmall.pth"))
model.eval()

tp, ty = [], []
with torch.no_grad():
    for x, y in test_dl:
        x, y = x.to(device), y.to(device)
        out = model(x)
        tp += out.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()

print("\n🎯 TEST ACCURACY:", accuracy_score(ty, tp))
print("\n📄 CLASSIFICATION REPORT:\n")
print(classification_report(ty, tp, target_names=classes))

# =========================================================
# 🔟 SAVE FINAL MODEL
# =========================================================
torch.save(model.state_dict(), "ConvNeXtSmall_Final.pth")
print("✅ Final model saved")

# =========================================================
# 📈 11️⃣ PLOTTING ACCURACY, LOSS & LEARNING RATE
# =========================================================
epochs = range(1, EPOCHS + 1)

plt.figure(figsize=(18, 5))

# Accuracy
plt.subplot(1, 3, 1)
plt.plot(epochs, train_acc_hist, label="Train Accuracy")
plt.plot(epochs, val_acc_hist, label="Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Accuracy vs Epochs")
plt.legend()
plt.grid(True)

# Loss
plt.subplot(1, 3, 2)
plt.plot(epochs, train_loss_hist, label="Train Loss")
plt.plot(epochs, val_loss_hist, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Loss vs Epochs")
plt.legend()
plt.grid(True)

# Learning Rate
plt.subplot(1, 3, 3)
plt.plot(epochs, lr_hist)
plt.xlabel("Epochs")
plt.ylabel("Learning Rate")
plt.title("Learning Rate Schedule")
plt.grid(True)

plt.tight_layout()
plt.show()

# =========================================================
# 0️⃣ IMPORTS
# =========================================================
import os, glob, time
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image

import albumentations as A
from albumentations.pytorch import ToTensorV2

from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    precision_score, recall_score, f1_score,
    roc_curve, auc, precision_recall_curve, average_precision_score
)
from sklearn.preprocessing import label_binarize

import timm

# =========================================================
# 1️⃣ DEVICE
# =========================================================
device = "cuda" if torch.cuda.is_available() else "cpu"
print("🔥 Device:", device)

# =========================================================
# 2️⃣ AUTO-DETECT DATASET ROOT
# =========================================================
def find_dataset_root():
    for d in os.listdir("/content"):
        if "blood-group" in d.lower():
            return os.path.join("/content", d)
    raise FileNotFoundError("❌ Blood group dataset folder not found")

DATASET_PATH = find_dataset_root()
print("📂 Dataset Root:", DATASET_PATH)

# =========================================================
# 3️⃣ AUTO-DETECT TEST FOLDER
# =========================================================
if os.path.exists(os.path.join(DATASET_PATH, "test")):
    TEST_PATH = os.path.join(DATASET_PATH, "test")
elif os.path.exists(os.path.join(DATASET_PATH, "valid")):
    TEST_PATH = os.path.join(DATASET_PATH, "valid")
else:
    raise FileNotFoundError("❌ No test/valid folder found")

print("📂 Using Test Path:", TEST_PATH)

# =========================================================
# 4️⃣ CLASS NAMES (SAFE)
# =========================================================
classes = sorted([
    d for d in os.listdir(TEST_PATH)
    if os.path.isdir(os.path.join(TEST_PATH, d))
])

num_classes = len(classes)
print("🧬 Classes:", classes)

# =========================================================
# 5️⃣ TRANSFORMS
# =========================================================
test_tfms = A.Compose([
    A.Resize(224, 224),
    A.Normalize(),
    ToTensorV2()
])

# =========================================================
# 6️⃣ DATASET & DATALOADER
# =========================================================
class BloodDataset(Dataset):
    def __init__(self, root, tfm):
        self.files, self.labels = [], []
        self.tfm = tfm

        for idx, cls in enumerate(classes):
            imgs = glob.glob(os.path.join(root, cls, "*"))
            self.files.extend(imgs)
            self.labels.extend([idx] * len(imgs))

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        img = np.array(Image.open(self.files[idx]).convert("RGB"))
        img = self.tfm(image=img)["image"]
        return img, self.labels[idx]

test_ds = BloodDataset(TEST_PATH, test_tfms)
test_dl = DataLoader(test_ds, batch_size=64, shuffle=False)

print("🧪 Test Samples:", len(test_ds))

# =========================================================
# 7️⃣ LOAD TRAINED MODEL
# =========================================================
model = timm.create_model(
    "convnext_small",
    pretrained=False,
    num_classes=num_classes
)

model.load_state_dict(torch.load("Best_ConvNeXtSmall.pth", map_location=device))
model.to(device)
model.eval()

print("✅ Model Loaded Successfully")

# =========================================================
# 8️⃣ TESTING (NO TRAINING)
# =========================================================
y_true, y_pred, y_prob = [], [], []

with torch.no_grad():
    for x, y in test_dl:
        x = x.to(device)
        out = model(x)
        prob = torch.softmax(out, dim=1)

        y_true.extend(y)
        y_pred.extend(out.argmax(1).cpu().numpy())
        y_prob.extend(prob.cpu().numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_prob = np.array(y_prob)

# =========================================================
# 9️⃣ CORE METRICS
# =========================================================
print("\n🎯 TEST ACCURACY:", accuracy_score(y_true, y_pred))
print("\n📄 CLASSIFICATION REPORT:\n")
print(classification_report(y_true, y_pred, target_names=classes))

print("Macro F1-score :", f1_score(y_true, y_pred, average="macro"))
print("Weighted F1    :", f1_score(y_true, y_pred, average="weighted"))

# =========================================================
# 🔟 CONFUSION MATRIX
# =========================================================
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(
    cm, annot=True, fmt="d", cmap="Blues",
    xticklabels=classes, yticklabels=classes
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

# =========================================================
# 1️⃣1️⃣ ROC CURVE
# =========================================================
y_bin = label_binarize(y_true, classes=range(num_classes))

plt.figure(figsize=(7,6))
for i, cls in enumerate(classes):
    fpr, tpr, _ = roc_curve(y_bin[:, i], y_prob[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{cls} (AUC={roc_auc:.2f})")

plt.plot([0,1], [0,1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Multi-class ROC Curve")
plt.legend()
plt.grid(True)
plt.show()

# =========================================================
# 1️⃣2️⃣ INFERENCE SPEED
# =========================================================
x, _ = next(iter(test_dl))
x = x.to(device)

for _ in range(10):
    _ = model(x)

start = time.time()
for _ in range(100):
    _ = model(x)
end = time.time()

fps = (100 * x.size(0)) / (end - start)
print(f"⚡ Inference Speed: {fps:.2f} FPS")

print("✅ Evaluation Complete — Ready for Paper")